import type { Request, Response, NextFunction } from 'express';

/**
 * Simple bearer-token middleware for the MCP HTTP endpoint.
 * Token is generated by `npm run pair` and stored in ~/.session-bridge/config.json.
 */
export function bearerAuth(expectedToken: string) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const header = req.header('authorization') || req.header('Authorization');
    if (!header) {
      res.status(401).json({ error: 'Missing Authorization header' });
      return;
    }
    const match = /^Bearer\s+(.+)$/i.exec(header.trim());
    if (!match) {
      res.status(401).json({ error: 'Authorization must be Bearer <token>' });
      return;
    }
    const token = match[1]!.trim();
    if (!token || token !== expectedToken) {
      res.status(403).json({ error: 'Invalid bearer token' });
      return;
    }
    next();
  };
}
